gridOxides:
  accessGroup: /vo.plgrid.pl/testbed-groups/plggoxides

grid:
  identityConfig: classpath:grid-local.properties
#  idpUrl: https://unity.grid.icm.edu.pl/testbed-portal/saml2unicoreIdp-web
  idpUrl: https://unicoreportal.grid.icm.edu.pl/testbed-portal/saml2unicoreIdp-web
  registry: https://hyx.grid.icm.edu.pl:8080/UNICORE-PORTAL/services/Registry?res=default_registry
  targetUrl: https://localhost:8443/oxides/authn

unicore.identityConfig: classpath:grid-local.properties
unicore.registryUri: https://hyx.grid.icm.edu.pl:8080/UNICORE-PORTAL/services/Registry?res=default_registry

server:
  port: 8443
  ssl:
    keyStore: classpath:keystores/sample.jks
    keyStorePassword: secret
    keyPassword: password
#    clientAuth: NEED

logging.level.org.springframework.security: INFO
