openOxides:
  groupName: /vo.plgrid.pl

gridOxides:
  accessGroup: /
  applicationName: Bash shell
#  applicationVersion: 4.1.2
  jobPrefix: _OpenOxides__
  resultsUrl: http://openoxides.icm.edu.pl/data/results.json

multipart:
  maxFileSize: 16MB
  maxRequestSize: 64MB

#spring.resources.add-mappings: false

logging.level.: INFO
logging.level.org.apache.cxf.service.factory.ReflectionServiceFactoryBean: FATAL
logging.level.pl.edu.icm.oxides: DEBUG
logging.level.pl.edu.icm.oxides.unicore.site.job: TRACE
