openOxides.groupName: /vo.plgrid.pl

unity-idm:
  enable: true
  idpUrl: https://unity.grid.icm.edu.pl/unicore-portal/saml2unicoreIdp-web
  idpSloUrl: https://unity.grid.icm.edu.pl/unicore-portal/SLO-WEB
  targetUrl: https://localhost:8443/authn/sign-in

gridOxides:
  accessGroup: /
  applicationName: Bash shell
#  applicationVersion: 4.1.2
  jobPrefix: _OpenOxides__
  resultsUrl: http://openoxides.icm.edu.pl/data/results.json

feeds:
  sources:
    - url: https://www.unicore.eu/feed
      count: 3
    - url: https://unicore-life.github.io/feed
      count: 1

multipart:
  maxFileSize: 16MB
  maxRequestSize: 64MB

security:
  basic.enabled: false
  enable-csrf: true

server.session.cookie:
  http-only: true
  secure: true

spring:
  mvc.dispatch-trace-request: true
#  resources.add-mappings: true
  thymeleaf.cache: false

logging.level.: INFO
logging.level:
  org.apache.cxf.service.factory.ReflectionServiceFactoryBean: FATAL
  pl.edu.icm.oxides: DEBUG
  pl.edu.icm.oxides.unicore.site.job: TRACE
