openOxides:
  groupName: /vo.plgrid.pl

grid:
  identityConfig: grid.properties
  idpUrl: https://unity.grid.icm.edu.pl/testbed-portal/saml2unicoreIdp-web
#  registry: https://hyx.grid.icm.edu.pl:8080/ICM-HYDRA/services/Registry?res=default_registry
  registry: https://hyx.grid.icm.edu.pl:8080/UNICORE-PORTAL/services/Registry?res=default_registry
#  registry: https://unicore.grid.icm.edu.pl:8080/PLGRID/services/Registry?res=default_registry
  targetUrl: https://localhost:8443/oxides/authn

gridOxides:
  accessGroup: /vo.plgrid.pl/main/groups/plggoxides
  applicationName: Bash shell
#  applicationVersion: 4.1.2
  jobPrefix: _OpenOxides__
  resultsUrl: http://openoxides.icm.edu.pl/data/results.json

server:
  port: 8443
  ssl:
    keyStore: classpath:keystores/sample.jks
    keyStorePassword: secret
    keyPassword: password
#    clientAuth: NEED

multipart:
  maxFileSize: 16MB
  maxRequestSize: 64MB

#spring.resources.add-mappings: false

logging.file: oxides-grid-portal.log

logging.level.: INFO
logging.level.org.apache.cxf: FATAL
logging.level.pl.edu.icm.oxides: DEBUG
logging.level.pl.edu.icm.oxides.unicore.site.job: TRACE
