gridOxides:
  accessGroup: /vo.plgrid.pl/main/groups/plggoxides

grid:
  identityConfig: grid-prod.properties
  idpUrl: https://unity.grid.icm.edu.pl/unicore-portal/saml2unicoreIdp-web
  targetUrl: https://oxides.grid.icm.edu.pl/oxides/authn

server:
  port: 443
  ssl:
    keyStore: /opt/plgrid/certificates/oxides-grid-portal.jks
    keyStorePassword: the!oxides
    keyPassword: the!oxides

logging.file: /tmp/oxides-grid-portal.log
