gridOxides:
  accessGroup: /vo.plgrid.pl/groups/plggoxides

grid:
  identityConfig: config/grid.properties
  idpUrl: https://unity.grid.icm.edu.pl/unicore-portal/saml2unicoreIdp-web
  registry: https://hyx.grid.icm.edu.pl:8080/UNICORE-PORTAL/services/Registry?res=default_registry
  targetUrl: https://oxides.grid.icm.edu.pl/oxides/authn

server:
  port: 443
  ssl:
    keyStore: /opt/plgrid/certificates/oxides-grid-portal.jks
    keyStorePassword: the!oxides
    keyPassword: the!oxides

logging.file: /tmp/oxides-grid-portal.log
