openOxides:
  groupName: /vo.plgrid.pl

grid:
#  registry: https://hyx.grid.icm.edu.pl:8080/ICM-HYDRA/services/Registry?res=default_registry
  registry: https://hyx.grid.icm.edu.pl:8080/UNICORE-PORTAL/services/Registry?res=default_registry
#  registry: https://unicore.grid.icm.edu.pl:8080/PLGRID/services/Registry?res=default_registry
  idpUrl: https://unity.grid.icm.edu.pl/testbed-portal/saml2unicoreIdp-web
  targetUrl: https://localhost:8443/oxides/authn
#  targetUrl: https://alfred.mat.umk.pl:8443/authn/saml

gridOxides:
  applicationName: Date
  applicationVersion: 1.0

server:
  port: 8443
  ssl:
    keyStore: classpath:keystores/sample.jks
    keyStorePassword: secret
    keyPassword: password
#    clientAuth: NEED

multipart:
  maxFileSize: 16MB
  maxRequestSize: 64MB

logging.level.pl.icm.edu.oxides: DEBUG
logging.level.: INFO
